MultipartKit V5
vapor/multipart-kit pull request #100
Opened 2024-10-07 18:52 UTC by ptoffy

2024-10-23 15:34 UTC, adam-fowler reviewed
Some initial comments.

2024-10-23 15:34 UTC, adam-fowler commented on Sources/MultipartKit/MultipartParser+AsyncStream.swift
> +public struct MultipartParseSequence: AsyncSequence {
You could use a generic parameter on the type to avoid the need for AnyAsyncSequence eg
```swift
public struct MultipartParseSequence<Base: AsyncSequence> where Base.Element == ArraySlice<UInt8> {
    let baseSequence: Base
    public init(boundary: String, baseSequence: Base) {
    }
}
```
If you need a type erased version I'm sure you could add a wrapper `AnyMultipartParseSequence`

2024-10-23 15:34 UTC, adam-fowler commented on Sources/MultipartKit/MultipartParser.swift
> +    mutating func append(buffer: ArraySlice<UInt8>) {
Perhaps append can take a generic collection. There is a good chance the source of the Multipart data is a ByteBuffer.
```swift    
mutating func append<Buffer: Collection<UInt8>>(buffer: Buffer) {
    switch self.state {
    case .initial:
        self.state = .parsing(.boundary, .init(buffer))
        ...
```

2024-10-23 15:34 UTC, adam-fowler commented on Sources/MultipartKit/MultipartParser+AsyncStream.swift
> +    public init<AS: AsyncSequence & Sendable>(boundary: String, buffer: AS) where AS.Element == ArraySlice<UInt8> {
If you make `MultipartParser.append` take a generic collection, you can change the requirement on `AS.Element` to be `AS.Element: Collection<UInt8>`

2024-10-23 15:34 UTC, adam-fowler commented on Sources/MultipartKit/MultipartParser.swift
> +    private mutating func parseBody(from buffer: ArraySlice<UInt8>) -> ReadResult {
It looks like parseBody only returns complete bodies. is this correct? This won't be very memory efficient if the body is large.

2024-10-23 15:51 UTC, ptoffy commented on Sources/MultipartKit/MultipartParser.swift
> +    private mutating func parseBody(from buffer: ArraySlice<UInt8>) -> ReadResult {
Not exactly: it returns a body chunk for each line of content. You can see in the tests how that gets parsed. However I'm not sure how multipart encodes data such as images. If it's just a huge string of binary data on one line it might make problems. We'd have to define a chunk size in that case

2024-10-24 07:00 UTC, adam-fowler commented on Sources/MultipartKit/MultipartParser.swift
> +    private mutating func parseBody(from buffer: ArraySlice<UInt8>) -> ReadResult {
You'll need to support binary files. You don't need to define a chunk size though. Just pass the body chunks as you receive them. 

Is your current body parsing code assuming the content is ASCII?

2024-10-24 14:20 UTC, ptoffy commented on Sources/MultipartKit/MultipartParser.swift
> +    private mutating func parseBody(from buffer: ArraySlice<UInt8>) -> ReadResult {
It shouldn't be ASCII specific besides the boundary check

2024-10-25 08:18 UTC, adam-fowler commented on Sources/MultipartKit/MultipartParser.swift
> +    private mutating func parseBody(from buffer: ArraySlice<UInt8>) -> ReadResult {
You are checking for CRLF in data that could be binary. Newlines are not a concept in binary data. The check for CRLF only makes sense if the source data is text.

Is there a reason you want to break up the body into lines?

2024-10-30 12:05 UTC, ptoffy commented
@adam-fowler Do you want to take a look at this again and see if stuff makes more sense now? I added in some binary data (which even contains hex-CRLF 😄) to the tests so it should be able to parse anything now

2024-11-18 20:10 UTC, ptoffy commented
@Joannis @simonjbeaumont @czechboy0 pulling you into this so you can take a look if you want

2024-11-19 08:35 UTC, Joannis commented on Package.swift
> +// swift-tools-version:6.0
Is this necessary?

2024-11-19 08:35 UTC, Joannis commented on Package.swift
> +        .watchOS(.v8),
Are these bump necessary as well? macOS 15 is also a fair bit higher can iOS 15

2024-11-19 08:35 UTC, Joannis commented on Package.swift
> +        .package(url: "https://github.com/apple/swift-http-types.git", from: "1.3.0"),
Love this

2024-11-19 08:35 UTC, Joannis commented on Sources/MultipartKit/FormDataDecoder/FormDataDecoder.SingleValueContainer.swift
> +import Foundation
`FoundationEssentials` might be more fitting?

2024-11-19 08:35 UTC, Joannis commented on Sources/MultipartKit/FormDataDecoder/FormDataDecoder.swift
> +        try decode(D.self, from: Array(string.utf8), boundary: boundary)
This makes a copy from `string`, can't we use `withContiguousMemoryIfAvailable`?

2024-11-19 08:35 UTC, Joannis commented on Sources/MultipartKit/MultipartParser+parse.swift
> +        parser.append(buffer: data)
Is it necessary to copy data out before parsing?

2024-11-19 08:58 UTC, ptoffy commented on Sources/MultipartKit/FormDataDecoder/FormDataDecoder.swift
> +        try decode(D.self, from: Array(string.utf8), boundary: boundary)
Mhh I don't think that would work any better because we need the Collection there. We can't pass in the raw bytes and if we're copying them to an array we're still making a copy at that point right?

2024-11-19 08:59 UTC, ptoffy commented on Sources/MultipartKit/MultipartParser+parse.swift
> +        parser.append(buffer: data)
This way we avoid a whole bunch of `needMoreData` returns from the parser

2024-11-19 09:01 UTC, ptoffy commented on Package.swift
> +// swift-tools-version:6.0
With 6.1 being branched I don't think we should go lower than 5.10, and at that point might as well go 6.0. Plus we're currently using `Mutex` which yes _can_ be replaced but why

2024-11-19 10:00 UTC, adam-fowler commented on Sources/MultipartKit/FormDataEncoder/FormDataEncoder.swift
> +    public func encode<E: Encodable, Body: MultipartPartBodyElement>(_ encodable: E, boundary: String) throws -> Body
Can we have the generic parameter as a function parameter as well eg
```swift
public func encode<E: Encodable, Body: MultipartPartBodyElement>(
    _ encodable: E, 
    boundary: String, 
    to: Body.Type = Body.self
) throws -> Body
```

2024-11-19 10:01 UTC, Joannis commented on Package.swift
> +// swift-tools-version:6.0
I noticed a fair amount of people use `latest - 1` still, that's the main _why_. I wouldn't go for 5.9 at this point anyways, but I think if you're using newer features like mutex - that's fair.

2024-11-19 10:04 UTC, Joannis commented on Sources/MultipartKit/FormDataDecoder/FormDataDecoder.swift
> +        try decode(D.self, from: Array(string.utf8), boundary: boundary)
Since you're doing an `.append` on the parser you're right that you're already making a copy. Except right now you're making _two_ copies of the same data, and each time you're also allocating space for that data.

2024-11-19 10:06 UTC, Joannis commented on Sources/MultipartKit/MultipartParser+parse.swift
> +        parser.append(buffer: data)
Could it be restructured to be `parseOrAppend` then?

```swift
if parserBuffer.isEmpty {
  let result = parser.parse(data)
  if result == .needMoreData {
    parser.append(data)
  }
} else {
  parser.append(data)
  parser.parse()
}
```

2024-11-19 10:14 UTC, adam-fowler commented on Sources/MultipartKit/FormDataEncoder/Storage.swift
> +protocol DataContainer<Body>: Sendable {
Why do a bunch of the internal types of the encoder have to conform to Sendable? These are only accessed from a single thread surely.

2024-11-19 10:16 UTC, adam-fowler commented on Sources/MultipartKit/FormDataEncoder/Storage.swift
> +    private let box: Mutex<OrderedDictionary<String, Storage<Body>>> = .init(.init())
If this didn't need to be Sendable you wouldn't need to wrap the value access in a Mutex. You also seem to have a private member `_value` which isn't used

2024-11-19 10:17 UTC, adam-fowler commented on Sources/MultipartKit/FormDataDecoder/FormDataDecoder+Decoder.swift
> +    struct Decoder<Body: MultipartPartBodyElement>: Sendable {
Does this need to be Sendable?

2024-11-19 10:18 UTC, adam-fowler commented on Sources/MultipartKit/FormDataEncoder/FormDataEncoder+Encoder.swift
> +    struct Encoder<Body: MultipartPartBodyElement>: Sendable where Body: RangeReplaceableCollection {
Does this need to be Sendable?

2024-11-19 10:43 UTC, adam-fowler commented on Sources/MultipartKit/MultipartParserAsyncSequence.swift
> +    }
As I understand it the user can receive a body as multiple MultipartSections if the underlying AsyncSequence has broken that body up. This is great as we don't want to pay the memory for large bodies if we can. But there are situations where we want to ensure we have a complete body section eg a block of data we want to run a JSON decode on.  Is it possible to add a helper function to the Iterator to do this? eg `Iterator.collectBody(upTo: memoryLimit)` which returns a header, complete body section

2024-11-19 10:49 UTC, ptoffy commented on Sources/MultipartKit/FormDataEncoder/FormDataEncoder.swift
> +    public func encode<E: Encodable, Body: MultipartPartBodyElement>(_ encodable: E, boundary: String) throws -> Body
I'll reply to the rest when I'm back home but writing to a `ByteBufferView` works

2024-11-19 10:56 UTC, adam-fowler commented on Sources/MultipartKit/FormDataEncoder/FormDataEncoder.swift
> +    public func encode<E: Encodable, Body: MultipartPartBodyElement>(_ encodable: E, boundary: String) throws -> Body
Yeah that works and you can create a ByteBuffer from that. Make the `to:` parameter even more important as it makes people consider what their output buffer should be.

2024-11-19 11:23 UTC, ptoffy commented on Sources/MultipartKit/FormDataEncoder/FormDataEncoder.swift
> +    public func encode<E: Encodable, Body: MultipartPartBodyElement>(_ encodable: E, boundary: String) throws -> Body
Isn't it more swifty to let it be inferred from the LHS? Explicitly if needed, e.g.
```swift
let result: [UInt8] = encode(...)
```

2024-11-19 11:25 UTC, adam-fowler commented on Package.swift
> +        .watchOS(.v8),
Mutex?

2024-11-19 13:33 UTC, adam-fowler commented on Sources/MultipartKit/FormDataEncoder/FormDataEncoder.swift
> +    public func encode<E: Encodable, Body: MultipartPartBodyElement>(_ encodable: E, boundary: String) throws -> Body
If you can infer it, that's great, but `result = encode(...)` does not provide enough detail. I personally think it is more swifty to infer what `result` is from the function call than infer the function that should be called based off what I expect it to return.

2024-11-19 14:07 UTC, ptoffy commented on Package.swift
> +// swift-tools-version:6.0
Well there's also using Swift Testing

2024-11-19 14:37 UTC, ptoffy commented on Sources/MultipartKit/FormDataEncoder/FormDataEncoder.swift
> +    public func encode<E: Encodable, Body: MultipartPartBodyElement>(_ encodable: E, boundary: String) throws -> Body
Cool - I guess it's more of a style thing but I'm not precious about it so happy to take your suggestion

2024-11-19 14:46 UTC, ptoffy commented on Sources/MultipartKit/FormDataEncoder/Storage.swift
> +    private let box: Mutex<OrderedDictionary<String, Storage<Body>>> = .init(.init())
Well `Storage` is shared across the various encoding containers and that might lead to issues

2024-11-19 14:48 UTC, ptoffy commented on Sources/MultipartKit/FormDataDecoder/FormDataDecoder+Decoder.swift
> +    struct Decoder<Body: MultipartPartBodyElement>: Sendable {
We can probably remove `Sendable` annotations across the decoders but encoding shares the storage state so I doubt that will even compile with Swift 6

2024-11-19 14:50 UTC, ptoffy commented on Sources/MultipartKit/FormDataEncoder/Storage.swift
> +    private let box: Mutex<OrderedDictionary<String, Storage<Body>>> = .init(.init())
I mean I'm open to suggestions if you believe this can be solved otherwise

2024-11-19 15:02 UTC, ptoffy commented on Sources/MultipartKit/FormDataDecoder/FormDataDecoder.swift
> +        try decode(D.self, from: Array(string.utf8), boundary: boundary)
No, I mean we can't pass the raw pointer to the decode method because it expects the collection of bytes, so this can't be done
```swift
try string.utf8.withContiguousStorageIfAvailable { bytes in
    decode(D.self, from: bytes, boundary: boundary)
} ?? decode(D.self, from: Array(string.utf8), boundary: boundary)
```
And if we were to do something like 
```swift
if let bytes = string.utf8.withContiguousStorageIfAvailable(Array.init) {
    try decode(D.self, from: bytes, boundary: boundary)
} else {
    try decode(D.self, from: Array(string.utf8), boundary: boundary)
}
```
we're still initialising an array with the raw bytes so this doesn't really save us a copy. 
Unless you mean a different way of using `withContiguousStorageIfAvailable `

2024-11-19 15:05 UTC, ptoffy commented on Sources/MultipartKit/MultipartParser+parse.swift
> +        parser.append(buffer: data)
But why? We're just doing that once at the beginning, this is the sync parse

2024-11-19 15:32 UTC, adam-fowler commented on Sources/MultipartKit/MultipartParserAsyncSequence.swift
> +    }
Yes just one part of the message eg I have a Multipart message with a zip file in there plus some metadata. I want to save the zip files to disk (using the least amount of memory possible ie streaming it) but parse the metadata with Codable so need the whole of it in memory.

2024-11-19 15:34 UTC, adam-fowler commented on Sources/MultipartKit/FormDataEncoder/Storage.swift
> +    private let box: Mutex<OrderedDictionary<String, Storage<Body>>> = .init(.init())
Is Storage accessed from multiple tasks? Encoders are normally single threaded

2024-11-20 08:58 UTC, adam-fowler commented on Sources/MultipartKit/FormDataEncoder/Storage.swift
> +    private let box: Mutex<OrderedDictionary<String, Storage<Body>>> = .init(.init())
You would remove the Sendable conformance completely. It is not needed. The gain is you remove all the locks.

2024-11-20 09:23 UTC, ptoffy commented on Sources/MultipartKit/FormDataEncoder/Storage.swift
> +    private let box: Mutex<OrderedDictionary<String, Storage<Body>>> = .init(.init())
Right. I would've expected Swift 6 language mode to complain but apparently we're fine

2024-12-28 15:08 UTC, ptoffy commented on Sources/MultipartKit/MultipartParserAsyncSequence.swift
> +    }
Added https://github.com/vapor/multipart-kit/pull/100/commits/38bc3c1d94b90556cbdebfa21cbfb12522d09c4b#diff-0d53ff899089448c57c2915f2315bbf9d9e50f9a16caa3e2669249e84ff87d35R76

2025-01-01 16:18 UTC, 0xTim requested changes
Some comments. This is starting to look good and we're getting close to be able to tag an alpha I think. 

Would be good to get the performance tests set up so we can measure changes going forward and code coverage to see which edge cases we don't currently test

2025-01-01 16:18 UTC, 0xTim commented on Sources/MultipartKit/FormDataEncoder/Storage.swift
> +import Synchronization
What's this? And where do we use it?

2025-01-01 16:18 UTC, 0xTim commented on Sources/MultipartKit/MultipartParser.swift
> +        self.boundary = [45, 45] + ArraySlice(boundary.utf8)
Add a comment as to this magic number or change it to a static named variable

2025-01-01 16:18 UTC, 0xTim commented on Sources/MultipartKit/MultipartParser.swift
> +        switch buffer.getFirstRange(of: [13, 10] + boundary) {
Again magic numbers

2025-01-01 16:18 UTC, 0xTim commented on Sources/MultipartKit/MultipartParser.swift
> -    static let space: UInt8 = 9
Let's bring something like this back to make it clear what everything is

2025-01-01 16:18 UTC, 0xTim commented on Sources/MultipartKit/MultipartParser.swift
> -    private static let allowedHeaderFieldNameCharacterFlags: [Bool] = [
Where do we check for this now?

2025-01-01 16:57 UTC, adam-fowler commented on Sources/MultipartKit/FormDataEncoder/Storage.swift
> +import Synchronization
That'll be from when Paul was using a Mutex protected state, which got removed so this can go

2025-01-01 17:16 UTC, adam-fowler reviewed
Looking good. Maybe we should have two async sequences though. One that does the collation automatically and one that requires you to use `nextCollatedPart` when you want a collated part.

I would rename the current AsyncSequence `StreamingMultipartParserAsyncSequence` and add the following 
```swift
public struct MultipartParserAsyncSequence<BackingSequence: AsyncSequence>: AsyncSequence
where BackingSequence.Element: MultipartPartBodyElement & RangeReplaceableCollection {
    let streamingSequence: StreamingMultipartParserAsyncSequence<BackingSequence>

    public struct AsyncIterator: AsyncIteratorProtocol {
        public mutating func next() async throws -> MultipartSection<BackingSequence.Element>? {
            try await self.streamingIterator.nextCollatedPart()
        }

        var streamingIterator: StreamingMultipartParserAsyncSequence<BackingSequence>.AsyncIterator
    }

    public func makeAsyncIterator() -> AsyncIterator {
        return .init(streamingIterator: self.streamingSequence.makeAsyncIterator())
    }
}
```

2025-01-01 17:16 UTC, adam-fowler commented on Sources/MultipartKit/MultipartParserAsyncSequence.swift
> +                    headerFields.append(contentsOf: fields)
Is there no chance you can read a header part after having read body parts?

2025-01-01 17:22 UTC, adam-fowler commented on Sources/MultipartKit/MultipartParserAsyncSequence.swift
> +    public struct Iterator: AsyncIteratorProtocol {
You should probably call this `AsyncIterator` instead of `Iterator` which is the associated type for a Sequence

2025-01-01 18:22 UTC, ptoffy commented on Sources/MultipartKit/MultipartParser.swift
> -    private static let allowedHeaderFieldNameCharacterFlags: [Bool] = [
Here via `HTTPTypes` https://github.com/vapor/multipart-kit/blob/v5/Sources/MultipartKit/MultipartParser.swift#L171-L173

2025-01-01 18:32 UTC, ptoffy commented on Sources/MultipartKit/MultipartParserAsyncSequence.swift
> +                        headerFields = .init()
Well if there's different parts in a message there might other headers later and this empties them before possibly reading other ones

2025-01-01 18:43 UTC, ptoffy commented on Sources/MultipartKit/MultipartParserAsyncSequence.swift
> +                    headerFields.append(contentsOf: fields)
Yes there is if the message has different parts

2025-01-01 18:50 UTC, ptoffy commented on Sources/MultipartKit/MultipartParserAsyncSequence.swift
> +                    headerFields.append(contentsOf: fields)
FYI in this case `fields` will always have just one field because the original sequence returns single header fields and body chunks. I'm not sure if this is misleading and should be clarified somehow, either with docs or with a name change

2025-01-01 18:59 UTC, ptoffy commented
I agree with the proposed changes but I moved the `nextCollatedPart()` to simply be the `next()` method of the new sequence which makes more sense to me

2025-01-01 19:16 UTC, ptoffy commented on Sources/MultipartKit/MultipartSection.swift
> +public enum MultipartSection<Body: MultipartPartBodyElement>: Equatable, Sendable {
I hear you but I think not having this is more trouble than worth. Right now we can do
```swift
switch part {
case .headerFields(let fields): print(fields)
case .bodyChunk(let chunk): print(chunk)
case .boundary: ...
}
```
If we made it a structure we'd have either
```swift
switch part {
case .headerFields(): print(part.headerFields!) // or guard unwrap checking if we're in the right case, which is silly
case .bodyChunk(): print(part.bodyChunk!) 
case .boundary(): ...
}
```
or something like
```swift
part.handle(
  onHeaderFields: { fields in 
    print(fields)
  },
  onBodyChunk: { chunk in 
    print(chunk)
  },
  onBoundary: { end in 
    ...
  }
)
```
and none of these is particularly appealing IMHO. But I'm open to suggestions if you know of non-invasive way to hide the enum

2025-01-02 14:05 UTC, 0xTim approved these changes
Nothing blocking on my end. Once other comments have been resolved we can look at integrating this into projects to see how it actually works

2025-01-02 14:06 UTC, 0xTim commented on Sources/MultipartKit/MultipartSection.swift
> +public enum MultipartSection<Body: MultipartPartBodyElement>: Equatable, Sendable {
Lets keep it for now and see how we get on with a TODO to review

2025-01-04 17:10 UTC, Joannis commented on Sources/MultipartKit/MultipartSerializer.swift
> +            buffer.append(contentsOf: Array("--\(boundary)".utf8) + crlf)
Instead of copying the boundary into an array, write the leading tokens, boundary and CRLF separately. Saves copies and allocs, thus a lot of work.

2025-01-04 17:10 UTC, Joannis commented on Sources/MultipartKit/MultipartSerializer.swift
> +                buffer.append(contentsOf: Array("\(field.description)".utf8) + crlf)
Same here, you can easily prevent a copy

2025-01-04 17:11 UTC, Joannis commented on Sources/MultipartKit/MultipartSerializer.swift
> +        buffer.append(contentsOf: Array("--\(boundary)--".utf8) + crlf)
Unnecessary copy

2025-01-04 17:11 UTC, Joannis commented on Sources/MultipartKit/FormDataDecoder/FormDataDecoder.swift
> +        try decode(D.self, from: Array(string.utf8), boundary: boundary)
I would really prefer not copying unnecessarily in a library like this

2025-01-04 17:12 UTC, Joannis commented on Sources/MultipartKit/MultipartSerializer.swift
> +        let crlf = Array("\r\n".utf8)
CRLF is copied into this a lot. I would keep it as `"\r\n".utf8` and append those values. Don't copy it into an array if possible

2025-01-04 17:13 UTC, Joannis requested changes
My main (only) issue is that this library makes a lot of copies out of every byte carrier (String, Array etc)

2025-01-06 18:47 UTC, ptoffy commented on Sources/MultipartKit/MultipartSerializer.swift
> +        let crlf = Array("\r\n".utf8)
Actually I did add in https://github.com/vapor/multipart-kit/blob/v5/Sources/MultipartKit/Utilities.swift#L61 so using that now

2025-01-06 19:20 UTC, gwynne requested changes
Various nits

2025-01-06 19:20 UTC, gwynne commented on Sources/MultipartKit/FormDataDecoder/FormDataDecoder+SingleValueContainer.swift
> +                String(bytes: part.body, encoding: .utf8).flatMap(URL.init(string:)) as? T
```suggestion
                String(bytes: part.body, encoding: .utf8) as? T
            case let IntType as any FixedWidthInteger.Type:
                String(decoding: part.body, as: UTF8.self).flatMap(IntType.init) as? T
            case is Float.Type:
                String(decoding: part.body, as: UTF8.self).flatMap(Float.init) as? T
            case is Double.Type:
                String(decoding: part.body, as: UTF8.self).flatMap(Double.init) as? T
            case is Bool.Type:
                String(decoding: part.body, as: UTF8.self).flatMap(Bool.init) as? T
            case is Data.Type:
                Data(part.body) as? T
            case is URL.Type:
                String(decoding: part.body, as: UTF8.self).flatMap(URL.init(string:)) as? T
```
Also, for the "basic" types (`String`, integers, `Float`/`Double`, `Bool`) you get a significant speedup by implementing the individual non-generic `decode()` methods for those types rather than doing a runtime type check in the generic method.

2025-01-06 19:20 UTC, gwynne commented on Sources/MultipartKit/FormDataDecoder/FormDataDecoder+KeyedContainer.swift
> +                DecodingError.Context(
```suggestion
                .init(
```

2025-01-06 19:20 UTC, gwynne commented on Sources/MultipartKit/FormDataEncoder/FormDataEncoder+SingleValueContainer.swift
> +    func encode<T: Encodable>(_ value: T) throws {
Again, you see a speedup by implementing the individual non-generic `encode()` methods rather than doing runtime type checks in the generic method.

2025-01-06 19:20 UTC, gwynne commented on Sources/MultipartKit/StreamingMultipartParserAsyncSequence.swift
> +                    }
```suggestion
                case .success(.some(let part)):
                    return part
                case .success(_):
                    continue
```

2025-01-07 09:56 UTC, ptoffy commented on Sources/MultipartKit/StreamingMultipartParserAsyncSequence.swift
> +                    }
Not sure I'm a fan of this

2025-01-07 10:09 UTC, gwynne approved these changes

2025-01-07 10:12 UTC, dimitribouniol commented on Sources/MultipartKit/StreamingMultipartParserAsyncSequence.swift
> +                    }
If anything, I would explicitly call out the `.none` in the second case to make it explicit. (Also, reminder that `case .success(let part?)` is somehow valid syntax nobody remembers to use)

2025-01-07 17:06 UTC, MahdiBM commented on Sources/MultipartKit/MultipartSerializer.swift
>          for part in parts {
I haven't kept up with the PR but it looks like there is opportunity for some `buffer.reserveCapacity(minimumWritableBytes:)`s.

2025-01-07 17:11 UTC, 0xTim commented on Sources/MultipartKit/MultipartSerializer.swift
>          for part in parts {
I think I'd this point we should merge, add benchmarks (including allocations) and then iterate forward

2025-01-07 17:20 UTC, MahdiBM commented on Sources/MultipartKit/MultipartSerializer.swift
>          for part in parts {
sounds good, since that will be an optimization too.

2025-01-08 08:06 UTC, ptoffy commented on Sources/MultipartKit/MultipartSerializer.swift
>          for part in parts {
That's not so easy, the buffer isn't necessarily a `ByteBuffer`

2025-01-08 09:51 UTC, adam-fowler reviewed
> I agree with the proposed changes but I moved the `nextCollatedPart()` to simply be the `next()` method of the new sequence which makes more sense to me

While I can see the sense in this, I'm thinking of how this may be used. Given multipart files can come with sections of different structure, some you might want to stream and some you might want collated I think you should re-instate the `nextCollatedPart()`.

One other thing to consider. Nobody is ever going to want to stream headers, so collating them automatically makes sense.

I am trying this out with my swift package registry example just now. Will report back. To give you some context SwiftPM packages a file into a Multipart file consisting of headers for metadata, a metadata block, a headers for the package zip, and then the zip file of the package. I don't want to stream the first three sections but will want to stream the last.

2025-01-08 11:38 UTC, adam-fowler commented
Yeah by making me deal with streaming all the sections it is painful. Would be great if I could do 
```swift
let multipartStream = StreamingMultipartParserAsyncSequence(...)
let iterator = multipartStream.makeAsyncIterator()
while let part = try await iterator.next() {
    guard case .headerFields(let headers) else { continue }
    // is metadata
    if getParameter(headers[.contentDisposition].first, parameter: "name") == "metadata" {
        guard let metadata = iterator.nextCollatedBlock() else { throw Error() }
        parseMetadata(metadata)
    }
    // is archive
    if getParameter(headers[.contentDisposition].first, parameter: "name") == "archive" {
        while case .bodyChunk(let buffer) = try await iterator.next() {
            streamArchivePartToDisk(buffer)
        }
    }
}
```

2025-01-08 12:29 UTC, 0xTim commented
I think that's a reasonable request for the API. If you're happy @adam-fowler I think we should merge as is and then add the improved API going forward?

2025-01-08 12:54 UTC, ptoffy commented
@0xTim I think adding the change in this PR makes sense. I'll add it in this afternoon and then we can merge

2025-01-08 14:44 UTC, ptoffy commented
@adam-fowler I updated the code to work with your example and I can confirm this works
```swift
let stream = makeParsingStream(for: message)
var iterator = StreamingMultipartParserAsyncSequence(boundary: boundary, buffer: stream).makeAsyncIterator()

var accumulatedBody: [UInt8] = []

while let part = try await iterator.next() {
    guard case .headerFields(let fields) = part else { continue }

    if fields.getParameter(.contentDisposition, "name") == "id" {
        guard let id = try await iterator.nextCollatedPart() else {
            throw MultipartMessageError.unexpectedEndOfFile
        }
        #expect(id == .bodyChunk(ArraySlice("123e4567-e89b-12d3-a456-426655440000".utf8)))
    } else {
        while case .bodyChunk(let chunk) = try await iterator.next() {
            accumulatedBody.append(contentsOf: chunk)
        }
    }
}

#expect(accumulatedBody == pngData)
```
though I haven't added the test to the branch because I'm a bit reluctant in making `fields.getParameter()` public. We can always do that later if needed. If you're happy with this I'll merge now

2025-01-08 15:51 UTC, merged