Un-vendor the swift-collections implementation
vapor/multipart-kit pull request #83
Opened 2022-04-29 20:06 UTC by ahmdyasser

- add swift-collections as a dependency
- delete OrderedCollections folder

2022-04-29 22:55 UTC, siemensikkema commented
I had an old PR for this https://github.com/vapor/multipart-kit/pull/74 that is now a bit out of date but comparing that with this one I see that we should also adjust or delete the NOTICE.md file. Are there perhaps other references or comments that should be updated?

2022-04-29 22:57 UTC, siemensikkema commented
By the way, I think the reason that the other PR was never merged was because at the time we didn't want to bump the minimum Swift requirement but that is now irrelevant since Swift NIO requires 5.4. Maybe our Package.swift files should be updated to communicate that as well? @gwynne?

2022-04-30 09:15 UTC, ahmdyasser commented
> I had an old PR for this #74 that is now a bit out of date but comparing that with this one I see that we should also adjust or delete the NOTICE.md file. Are there perhaps other references or comments that should be updated?

Thanks for the tip!, I think I will delete the [Attribution](https://github.com/vapor/multipart-kit#attribution) part from README.md file

2022-04-30 13:44 UTC, 0xTim commented
I'll have a look at this in the next couple of days. We'll need to update Vapor first to bump the swift tools version so this can be pulled in. You'll also need to update CI as well but that might need to be done by @gwynne

2022-05-05 19:23 UTC, ahmdyasser commented
@0xTim The test failed because I forgot to import the `Collections` library to some files. How can I test this PR again?

2022-05-05 20:10 UTC, 0xTim commented
@ahmdyasser each commit needs approving until you've had your first PR merged unfortunately

2022-05-05 22:14 UTC, ahmdyasser commented
@0xTim  So should I do something or wait for someone to fix it?

2022-05-05 22:44 UTC, 0xTim commented
@ahmdyasser you can see the latest run. You need to update the manifest to bump the swift tools version to 5.4. I need to update the central CI matrix

2022-05-07 20:41 UTC, ahmdyasser commented
@0xTim  Hi Tim! there are failed test cases, should I do something to fix it or you will do it?

2022-05-08 11:28 UTC, 0xTim commented
@ahmdyasser It's working now. Will be a bit before we merge though because I need to update all of Vapor's dependents, then Vapor and then we can merge

2022-05-15 13:40 UTC, 0xTim requested changes
One small README update then good to merge

2022-05-15 13:40 UTC, 0xTim commented on README.md
>  ### Attribution
@ahmdyasser Can you remove this title as it doesn't point to anything now? Thanks!

2022-05-15 16:18 UTC, ahmdyasser commented
> One small README update then good to merge

done.

2022-05-15 16:31 UTC, 0xTim approved these changes
Thanks!

2022-05-15 16:48 UTC, 0xTim commented
Original comment:

> - add swift-collections as a dependency
> - delete OrderedCollections folder

2022-05-15 16:50 UTC, merged