Update README
vapor/multipart-kit pull request #91
Opened 2023-12-19 10:42 UTC by 0xTim

Update README with new Swift version etc

2023-12-19 10:46 UTC, ptoffy requested changes
LGTM but while we're at it I'd also update the image cc @gwynne

2023-12-20 10:57 UTC, 0xTim commented
LGTM - I can't approve as I was the OP!

2023-12-20 12:23 UTC, gwynne approved these changes
Reflexive self-approve per @0xTim's review

2023-12-20 12:24 UTC, ptoffy approved these changes

2023-12-20 12:36 UTC, merged