Add encoding function that returns Data. Fixes #94
vapor/multipart-kit pull request #95
Opened 2024-03-01 22:23 UTC by andrew804

Added `encodeToData` function to `FormDataEncoder` which returns Data instead of String.
Added `serializeToData` function to `MultipartSerializer` which returns Data instead of String.
Added `decode` function to `FormDataDecoder` which accepts Data as input.
Added test for encoding and decoding a jpeg image with the new Data functions.
Added test for encoding and decoding a jpeg image with the original String functions.
Added image.jpeg in /Utilities

This PR fixes https://github.com/vapor/multipart-kit/issues/94

2024-03-01 22:42 UTC, gwynne requested changes
A great start! Just a few nits, nothing major.

2024-03-01 22:42 UTC, gwynne commented on Sources/MultipartKit/FormDataDecoder/FormDataDecoder.swift
> +        buffer.writeBytes(data)
`import NIOFoundationCompat` and use `ByteBufferAllocator().buffer(data: data)`.

2024-03-01 22:42 UTC, gwynne commented on Sources/MultipartKit/MultipartSerializer.swift
> +        return Data(buffer.readableBytesView)
`import NIOFoundationCompat` and use `Data(buffer: buffer, byteTransferStrategy: .automatic)`.

And while you're at it, change the `String` version to use `String(buffer: buffer)` 🙂

2024-03-01 22:42 UTC, gwynne commented on Tests/MultipartKitTests/MultipartTests.swift
> +        let path = "/" + folder + "/Utilities/image.jpeg"
Please don't do this - if you're going to go to the trouble of adding it to the manifest as a package resource, use `Bundle.module.url(forResource:)` rather than misusing `#filePath` (yes, despite the fact that I advised someone else to do exactly that just last night 😆).

2024-03-01 22:42 UTC, gwynne commented on Sources/MultipartKit/FormDataEncoder/FormDataEncoder.swift
> +    /// - returns: `multipart/form-data`-encoded `String`.
```suggestion
    /// - Parameters:
    ///     - encodable: An `Encodable` item.
    ///     - boundary: The multipart boundary to use for encoding. This string must not appear in the encoded data.
    /// - Throws: Any errors encoding the model or serializing the data.
    /// - Returns: A `multipart/form-data`-encoded `String`.
```

This better matches the style of documentation comments in use elsewhere (or at least anywhere that I've been writing them 😅).

(And of course, update the comments for the other methods you've added accordingly.)

2024-03-01 22:42 UTC, gwynne commented on Sources/MultipartKit/FormDataEncoder/FormDataEncoder.swift
> +    public func encodeToData<E: Encodable>(_ encodable: E, boundary: String) throws -> Data {
```suggestion
    public func encodeToData(_ encodable: some Encodable, boundary: String) throws -> Data {
```
Since the package requires Swift 5.7, we can use the more concise form of the generic type here. (If only the syntax was flexible enough to do the same with the decode side of things 😅). The `<E: Encodable>` and `some Encodable` forms are so synonymous that switching between them is not a source compatibility break. (In fact, can you make the same change in the `String` version of the method above?)

2024-03-02 13:56 UTC, andrew804 commented on Sources/MultipartKit/MultipartSerializer.swift
> +        return Data(buffer.readableBytesView)
I used `ByteBuffer(data: data)`  instead but assume that’s the same.

2024-03-02 14:02 UTC, andrew804 commented
Thank you for your fast feedback! Hopefully I covered everything - please let me know if not or if you have any further comments.

2024-03-18 16:40 UTC, 0xTim approved these changes
LGTM - @gwynne anything else to add?

2024-03-20 14:33 UTC, 0xTim commented
@andrew804 Looks like this is failing in CI

2024-03-26 08:37 UTC, andrew804 commented
@0xTim the failing test is the one that tests for encoding and decoding a jpeg image with the original string functions which highlights the original bug ie the original bug is still present, using the string encoding and decoding functions still corrupts the data.

Therefore I could either 1) add a warning in the documentation to not use the string functions and instead use the data functions for encoding and decoding images, then just remove the failing test or 2) remove the troublesome string functions entirely and include this PR in the next major release.

Unless you have any other suggestion, what would you prefer?

2025-02-26 15:25 UTC, ptoffy commented
Hey @andrew804 thanks for this, however I'm closing it as this is fixed in MultipartKit 5. You can simply use the generic encoding function 
```swift
let encoded = try FormDataEncoder().encode(object, boundary: "hello", to: [UInt8].self)
```

2025-02-26 15:25 UTC, closed without merging